FROM python:3.12-slim

# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

COPY --chown=1000:1000 . /app
WORKDIR ${FOLDER}

# Install Node.js and nodemon for easy watch mode with Python
USER root
RUN apt-get update \
    && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g nodemon \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER 1000:1000

# Setup venv
ENV PATH="$FOLDER/.venv/bin:$PATH"

EXPOSE 8000
ENV PORT=8000
ENV HOST="0.0.0.0"

CMD ["/usr/local/bin/nodemon", "--exec", ".venv/bin/python src/main.py"]
