apiVersion: apps/v1
{{- if eq .Values.stage "development"}}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  {{- if eq .Values.stage "development"}}
  serviceName: app
  {{- else }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  {{- end }}
  replicas: {{ ternary 1 0 .Values.enabled }}
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: diploi-pull-secret
      {{- if eq .Values.stage "development"}}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: install-dependencies
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              if [ -f pyproject.toml ]; then
                echo "Pyproject.toml found, installing dependencies with uv" && \
                uv sync --frozen --no-cache --link-mode=copy
              elif [ -f requirements.txt ]; then
                echo "requirements.txt found, installing dependencies with pip" && \
                uv venv .venv --clear && \
                uv pip install --python .venv/bin/python -r requirements.txt --link-mode=copy
              else
                echo "No dependency definition found" >&2
                exit 1
              fi && \
              cp --remove-destination "$(readlink /app{{ .Values.folder }}/.venv/bin/python)" /app{{ .Values.folder }}/.venv/bin/python 2>/dev/null || :
          workingDir: /app{{ .Values.folder }}
          volumeMounts:
            - name: app-mount
              mountPath: /app
      {{- end }}
      containers:
        - name: app
          image: {{ .Values.images.app }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          {{- if eq .Values.stage "development" }}
          {{- with .Values.containerCommands.developmentStart }}
          command:
            - /bin/sh
            - -c
            - |
          {{ . | nindent 14 }}
          {{- end }}
          {{- else }}
          {{- with .Values.containerCommands.productionStart }}
          command:
            - /bin/sh
            - -c
            - |
          {{ . | nindent 14 }}
          {{- end }}
          {{- end }}
          env:
            {{- range .Values.env }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            {{- if hasKey .Values.storage "code" }}
            - name: app-mount
              mountPath: /app
            {{- end }}
      volumes:
        {{- if hasKey .Values.storage "code" }}
        - name: app-mount
          hostPath:
            path: {{ .Values.storage.code.hostPath }}
        {{- end }}
